config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: %i[index show new create] do
    member do
      resources :bookmarks, only: %i[new create]
    end
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, :list_id, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:id])
    @bookmark = @list.bookmarks.new
  end

  def create
    @list = List.find(params[:id])
    @bookmark = @list.bookmarks.create(bookmark_params)
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= simple_form_for [@bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all, label_method: :title, value_method: :id %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<nav class = 'navbar-lewagon'>
  <i class="fa-solid fa-film fa-2xl"></i>
  <div>
    <%= link_to 'My lists', lists_path %>
    <%= link_to 'New list', new_list_path %>
  </div>
</nav>

app/views/lists/index.html.erb
<%= render 'navbar' %>

<div class = 'banner'>
  <h1>Save any kind of movies</h1>
</div>


<div style = 'display: flex; justify-content: space-evenly;'>
  <% @lists.each do |l| %>
    <div class="card" style="width: 72rem; margin: 50px;">
    <%= image_tag asset_path("#{l.name.downcase}.jpg"), class: "card-img-top"%>
    <div class="card-body">
      <h5 class="card-title"><%= l.name %></h5>
      <h1><%= link_to 'See more', list_path(l), class: 'btn btn-primary' %></h1>
    </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render 'navbar' %>

<%= simple_form_for(@list) do |l| %>
  <%= l.input :name %>
  <%= l.submit %>
<% end %>

app/views/lists/show.html.erb
<%= render 'navbar' %>

<h1><%= @list.name %></h1>
<% @list.bookmarks.each do |b| %>
  <p><%= b.movie.title %> : <%= b.comment %></p>
  <p><%= link_to 'Delete', bookmark_path(b), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
  <% end %>

<%= link_to 'Add new Bookmark', new_bookmark_path(@list) %>